name: CI Build and Notify
on:
  push:
    branches:
      - main    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Build
        run: |
          echo "Building the project..."
          exit 1
  notify:
    needs: build
    if: always()
    uses: KeezAdmin/infra-reusable-ops/.github/workflow/failure-notif.yaml@main
    secrets: inherit
    with:
      channel-id: 'general'
      job-status: ${{ needs.build.result }}
      message: "The build completed with status `${{ needs.build.result }}` in `2kg-coretech/bannana-job` on branch `${{ github.ref_name }}`."
        
